### ISSUE TITLE
Video input does not start

### ISSUE THREAD

**Issue by orlandobianco** [DeepARSDK/quickstart-web-js-npm#2]
I've installed the app on a vps, I've pasted my sdk key in index.js (I've tried with and without  ' ', but it does not work

 the app is here:  https://bilda.studio/quickstart-web-js-npm-main/public/index.html

in the chrome console I see this error
Failed to load resource: the server responded with a status of 404 ()  <--- referred to main.js
can it be some problem with the firewall of my vps?

I'm doing some adjustment by myself so don't mind other errors if visiting the webpage, assume I've done the steps provided in this repo

-uploaded the directory to my web server
-put my sdk key in the right spot
-npm install
-npm run dev

**Comment by omarsalem15** [comment]
@orlandobianco 
@DishoD 
@MateGasparini 

i have the same problem 
when i upload the project folders and files to the server it doesn't open the camera

**Comment by DishoD** [comment]
Can I have some more info please?

- What version of the SDK are you using?
- Can you share code snippets of integration?
- Are you using any bundler?
- How is the WASM file being fetched?

**Comment by igor-aradski** [comment]
Closed due to lack of current information. If you are experiencing the issue please leave a comment.
